//  src/config/tools.ts

import type { Tool } from '@/types/tool';

export const localToolsData: Tool[] = [
  // --- 社交媒体 ---
  {
    id: "social-1",
    name: "知乎",
    url: "https://www.zhihu.com/",
    description: "高质量的问答社区和创作者聚集的原创内容平台。",
    category: "社交媒体",
    tags: ["问答", "知识分享", "社区"],
  },
  {
    id: "social-2",
    name: "新浪微博",
    url: "https://weibo.com/",
    description: "随时随地发现新鲜事！汇聚热门资讯、明星动态的社交媒体平台。",
    category: "社交媒体",
    tags: ["热搜", "新闻", "社交"],
  },
  {
    id: "social-3",
    name: "哔哩哔哩",
    url: "https://www.bilibili.com/",
    description: "国内知名的视频弹幕网站，涵盖动漫、游戏、生活等多元内容。",
    category: "社交媒体",
    tags: ["B站", "视频", "动漫", "弹幕"],
  },
  {
    id: "social-4",
    name: "抖音",
    url: "https://www.douyin.com/",
    description: "记录美好生活的短视频平台。",
    category: "社交媒体",
    tags: ["短视频", "直播"],
  },
  {
    id: "social-5",
    name: "小红书",
    url: "https://www.xiaohongshu.com/",
    description: "年轻人的生活方式平台和消费决策入口。",
    category: "社交媒体",
    tags: ["生活方式", "种草", "社区"],
  },

  // --- 开发工具 ---
  {
    id: "dev-1",
    name: "GitHub",
    url: "https://github.com",
    description: "全球最大的代码托管平台和开发者社区。",
    category: "开发工具",
    tags: ["Git", "版本控制", "开源", "协作"],
  },
  {
    id: "dev-2",
    name: "GitLab",
    url: "https://gitlab.com/",
    description: "一个完整的 DevOps 平台，提供从项目规划到监控的全方位功能。",
    category: "开发工具",
    tags: ["Git", "DevOps", "CI/CD"],
  },
  {
    id: "dev-3",
    name: "Docker",
    url: "https://www.docker.com/",
    description: "开源的应用容器引擎，让开发者可以打包应用及依赖包到一个可移植的容器中。",
    category: "开发工具",
    tags: ["容器化", "虚拟化", "部署"],
  },
  {
    id: "dev-4",
    name: "Rust",
    url: "https://www.rust-lang.org/",
    description: "一门赋予每个人构建可靠且高效软件能力的语言。",
    category: "开发工具",
    tags: ["编程语言", "系统编程", "安全"],
  },
  {
    id: "dev-5",
    name: "CSDN",
    url: "https://www.csdn.net/",
    description: "专业的中文 IT 技术社区，提供博客、论坛、学习课程等资源。",
    category: "开发工具",
    tags: ["技术社区", "博客", "中文"],
  },
  {
    id: "dev-6",
    name: "力扣 (LeetCode)",
    url: "https://leetcode.cn/",
    description: "提升编程技能，准备技术面试的在线评测平台。",
    category: "开发工具",
    tags: ["算法", "数据结构", "面试"],
  },
   {
    id: "dev-7",
    name: "Webhooks",
    url: "https://webhook.site/",
    description: "轻松测试、调试和检查 Webhooks 和 HTTP 请求的工具。",
    category: "开发工具",
    tags: ["API", "调试", "测试", "HTTP"],
  },

  // --- 游戏相关 ---
  {
    id: "game-1",
    name: "Epic Games",
    url: "https://store.epicgames.com/",
    description: "Epic Games 商店，提供 PC 游戏购买、下载及每周免费游戏。",
    category: "游戏相关",
    tags: ["游戏商店", "喜加一"],
  },
  {
    id: "game-2",
    name: "原神",
    url: "https://ys.mihoyo.com/",
    description: "由米哈游开发的开放世界冒险游戏。",
    category: "游戏相关",
    tags: ["米哈游", "开放世界", "RPG"],
  },
  {
    id: "game-3",
    name: "明日方舟",
    url: "https://ak.hypergryph.com/",
    description: "鹰角网络开发的策略塔防游戏。",
    category: "游戏相关",
    tags: ["塔防", "鹰角"],
  },
  {
    id: "game-4",
    name: "PUBG",
    url: "https://pcrefresh.pubg.com/",
    description: "《绝地求生》，一款战术竞技类射击游戏。",
    category: "游戏相关",
    tags: ["大逃杀", "射击", "FPS"],
  },
   {
    id: "game-5",
    name: "LPL 官网",
    url: "https://lpl.qq.com/",
    description: "英雄联盟职业联赛官方网站，包含赛程、新闻和视频。",
    category: "游戏相关",
    tags: ["电竞", "英雄联盟", "赛事"],
  },
  {
    id: "game-6",
    name: "小黑盒",
    url: "https://www.xiaoheihe.cn/",
    description: "以玩家为核心的游戏社区，提供战绩查询、游戏资讯等服务。",
    category: "游戏相关",
    tags: ["游戏社区", "战绩查询"],
  },

  // --- 生活娱乐 ---
  {
    id: "life-1",
    name: "QQ音乐",
    url: "https://y.qq.com/",
    description: "千万正版高品质曲库，新歌热歌天天更新的在线音乐平台。",
    category: "生活娱乐",
    tags: ["音乐", "听歌"],
  },
  {
    id: "life-2",
    name: "网易云音乐",
    url: "https://music.163.com/",
    description: "一个以歌单、社交、大牌推荐为核心的音乐平台。",
    category: "生活娱乐",
    tags: ["音乐", "评论", "歌单"],
  },
  {
    id: "life-3",
    name: "YouTube",
    url: "https://www.youtube.com/",
    description: "全球最大的视频分享网站。",
    category: "生活娱乐",
    tags: ["视频", "全球"],
  },
  {
    id: "life-4",
    name: "爱奇艺",
    url: "https://www.iqiyi.com/",
    description: "拥有海量、优质、高清网络视频的在线视频网站。",
    category: "生活娱乐",
    tags: ["影视", "电视剧", "综艺"],
  },
  {
    id: "life-5",
    name: "天猫精选",
    url: "https://www.tmall.com/",
    description: "理想生活上天猫！中国线上购物的地标网站。",
    category: "生活娱乐",
    tags: ["购物", "电商"],
  },
  {
    id: "life-6",
    name: "京东商城",
    url: "https://www.jd.com/",
    description: "专业的综合网上购物商城，销售超数万品牌、4020万种商品。",
    category: "生活娱乐",
    tags: ["购物", "电商", "物流"],
  },
  {
    id: "life-7",
    name: "斗鱼",
    url: "https://www.douyu.com/",
    description: "领先的弹幕式直播分享网站，提供高清、快捷、流畅的视频直播。",
    category: "生活娱乐",
    tags: ["直播", "游戏直播"],
  },
  {
    id: "life-8",
    name: "虎牙直播",
    url: "https://www.huya.com/",
    description: "技术驱动的互动娱乐直播平台，拥有众多游戏、娱乐主播。",
    category: "生活娱乐",
    tags: ["直播", "游戏直播"],
  },
  
  // --- 学习办公 ---
  {
    id: "study-1",
    name: "arXiv.org",
    url: "https://arxiv.org/",
    description: "提供物理、数学、计算机科学等领域学术论文预印本的开放获取网站。",
    category: "学习办公",
    tags: ["论文", "科研", "学术"],
  },
  {
    id: "study-2",
    name: "知网",
    url: "https://www.cnki.net/",
    description: "中国知识基础设施工程，提供期刊、硕博论文等学术资源的检索服务。",
    category: "学习办公",
    tags: ["论文", "中文", "数据库"],
  },
  {
    id: "study-3",
    name: "欧路词典",
    url: "https://www.eudic.net/",
    description: "专业的离线词典软件，支持多平台和丰富的扩展词库。",
    category: "学习办公",
    tags: ["词典", "英语学习"],
  },
  {
    id: "study-4",
    name: "有道词典",
    url: "https://dict.youdao.com/",
    description: "网易出品的多语种翻译与词典服务，支持屏幕取词和文档翻译。",
    category: "学习办公",
    tags: ["词典", "翻译"],
  },
  {
    id: "study-5",
    name: "中国研招网",
    url: "https://yz.chsi.com.cn/",
    description: "全国硕士研究生招生报名和调剂指定网站。",
    category: "学习办公",
    tags: ["考研", "研究生", "官方"],
  },
  {
    id: "study-6",
    name: "教务系统",
    url: "https://[YOUR_SCHOOL_ACADEMIC_URL]", // <-- 请替换成你学校的教务系统链接
    description: "用于查询成绩、选课和查看教学计划的学校官方系统。",
    category: "学习办公",
    tags: ["学校", "选课", "成绩"],
  },
  {
    id: "study-7",
    name: "信息门户",
    url: "https://[YOUR_SCHOOL_PORTAL_URL]", // <-- 请替换成你学校的信息门户链接
    description: "整合校内新闻、通知和各项服务入口的综合信息平台。",
    category: "学习办公",
    tags: ["学校", "通知", "门户"],
  },

  // --- 效率提升 ---
  {
    id: "eff-1",
    name: "百度网盘",
    url: "https://pan.baidu.com/",
    description: "提供文件存储、备份、分享和查看服务的个人云存储产品。",
    category: "效率提升",
    tags: ["云盘", "存储", "分享"],
  },
  {
    id: "eff-2",
    name: "夸克网盘",
    url: "https://pan.quark.cn/",
    description: "夸克出品的云服务，主打高速下载和在线播放体验。",
    category: "效率提升",
    tags: ["云盘", "高速", "播放"],
  },
  {
    id: "eff-3",
    name: "Gmail",
    url: "https://mail.google.com/",
    description: "谷歌提供的免费电子邮件服务，拥有强大的搜索功能和垃圾邮件过滤。",
    category: "效率提升",
    tags: ["邮箱", "Google"],
  },
  {
    id: "eff-4",
    name: "163网易邮箱",
    url: "https://mail.163.com/",
    description: "网易公司推出的免费电子邮件服务，市场占有率领先。",
    category: "效率提升",
    tags: ["邮箱", "网易"],
  },
  {
    id: "eff-5",
    name: "Play Store",
    url: "https://play.google.com/",
    description: "谷歌为安卓设备开发的官方应用商店。",
    category: "效率提升",
    tags: ["应用商店", "Android"],
  },
];